FROM       mokevnin/hexlet-vagrant
# Dockerfile in the 'FROM' directive above can be found in hexlet-vagrant/base_image/Dockerfile
# it contains a list of preinstalled apps/langs/utils. For example, python is already installed.

RUN apt-get install -y redis-server
RUN pip install redis

# java
# RUN add-apt-repository -y ppa:webupd8team/java
# RUN apt-get update
# RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
# RUN apt-get install -y oracle-java7-installer

